// Route path (react-router pattern) -> document title. Kept separate from
// NAV_SECTIONS since several routes here (detail pages, /reports/financial)
// have no direct nav entry of their own.
export const PAGE_TITLES = [
  { path: '/home', title: 'Home' },
  { path: '/dashboard', title: 'Dashboard' },
  { path: '/properties', title: 'Properties' },
  { path: '/properties/:id', title: 'Property Details' },
  { path: '/tenants', title: 'Tenants' },
  { path: '/message-manager', title: 'Message Manager' },
  { path: '/tenant-messages', title: 'Tenant Messages' },
  { path: '/owners', title: 'Owners' },
  { path: '/leases', title: 'Leases' },
  { path: '/my-lease', title: 'My Lease' },
  { path: '/invoices', title: 'Invoices' },
  { path: '/payments', title: 'Payments' },
  { path: '/expenses', title: 'Expenses' },
  { path: '/my-payments', title: 'My Payments' },
  { path: '/maintenance', title: 'Maintenance Requests' },
  { path: '/maintenance/:id', title: 'Maintenance Request' },
  { path: '/work-orders', title: 'Work Orders' },
  { path: '/vendors', title: 'Vendors' },
  { path: '/inspections', title: 'Inspections' },
  { path: '/inspections/:id', title: 'Inspection Details' },
  { path: '/users', title: 'Users & Roles' },
  { path: '/roles/:id', title: 'Role Details' },
  { path: '/settings', title: 'Settings' },
  { path: '/reports/financial', title: 'Financial Reports' },
  { path: '/notifications', title: 'Notifications' },
  { path: '/audit-logs', title: 'Audit' },
];
